# Generated by Django 3.2.2 on 2021-07-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bidid', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('bidprice', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
