# Generated by Django 3.2.2 on 2021-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catid', models.IntegerField()),
                ('subcatname', models.CharField(max_length=50)),
                ('subcaticonname', models.CharField(max_length=50)),
            ],
        ),
    ]
