# Generated by Django 3.2.2 on 2021-07-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdescription',
            field=models.CharField(max_length=150),
        ),
    ]
